version: '3'

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  backendspring:
    image: 'slehel/springappdocker:newlatest'
    build:
      context: .
    container_name: backendspring
    depends_on:
      - postgresproductdb
    networks:
      - app-tier
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresproductdb:5432/product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MINIO_SERVER_ACCESS_KEY=minioadmin
      - MINIO_SERVER_SECRET_KEY=minioadmin
    ports:
      - 8080:8080

  postgresproductdb:
    image: 'postgres'
    container_name: postgresproductdb
    networks:
      - app-tier
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=product;
    ports:
      - 5432:5432

  frontendangular:
    image: 'slehel/angular-app:newlatest'
    container_name: frontendangular
    ports:
      - 4200:80
    depends_on:
      - backendspring
    networks:
      - app-tier
    environment:
      - MINIO_SERVER_ACCESS_KEY=minioadmin
      - MINIO_SERVER_SECRET_KEY=minioadmin


  miniowebshop:
      image: quay.io/minio/minio
      container_name: miniowebshop
      command: server --console-address ":9090" /home/shared
      ports:
        - 9000:9000
        - 9090:9090
      environment:
       MINIO_ACCESS_KEY: minioadmin
       MINIO_SECRET_KEY: minioadmin
       MINIO_ROOT_USER: minioadmin
       MINIO_ROOT_PASSWORD: minioadmin
       MINIO_SERVER_URL: http://localhost:9000
      networks:
        - app-tier
      depends_on:
        - frontendangular

  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://localhost:8161/admin (admin:admin)
    networks:
      - app-tier

  postgreskey:
    image: postgres
    container_name: postgreskey
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5555:5555
    networks:
      - app-tier


  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgreskey
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_HOSTNAME_ADMIN_URL: http://localhost:9990/auth/admin
    ports:
      - 9990:8080
    depends_on:
      - postgreskey
    networks:
      - app-tier